modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CreativeMD/PlayerRevive/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="playerrevive"
    logoFile="playerrevive.png"
    version="2.0.14"
    displayName="PlayerRevive"
    displayURL="https://modrinth.com/mod/playerrevive"
    displayTest="MATCH_VERSION"
    authors="CreativeMD"
    description='''Help your friends in need and revive them.'''

[[dependencies.playerrevive]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerrevive]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerrevive]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.20"

